#statusbarpadding
#statusbarshadow
.tahweem .absolute .top .bottom .left .right .noselect
#tafawwaq .sticky
#loadingbox .fixed .flex .big .bold
	.center
		[i18n=loading]
#dimmer .fixed @hidden
	#dimmertext
img #eqonahui .fixed .top .right @src(e.png)
#headerui .header @hidden [dir=1] .relative
#itlaa3 .fixed @hidden .flex
	.text
#taht3nsar .fixed @hidden .flex
	.text
button [template=checkbox] .checkbox .flex .row
	.center
		.icon [id=icon]
		label [id=label]