/* @TODO
 * this sub-module is supposed to connect backstack with the history api
 * it should do so transparently since mudeer already has a backstack logic
 * 
 * it can be as simple as root / view / sheet / dialog
 * basically four levels
 * 
 * any app that needs to run on platforms with a back button that needs the
 * history api (like android) should include this sub-module
 * */

;(function(){
	'use strict';
	var exiting = 0, backcount = 0, lasturiuponpop, evenlasturiuponpop, uuid = 0;
	
	// OLD LOGIC
	
	/*
	 * clear the history stack requires boilerplate code
	 * basically whenever you call history.back, you shouldn't call it again
	 * until you receive a popstate event from the browser, it is that ugly
	 * 
	 * so this module basically handles that automatically and you can register
	 * a callback to know when the back stack is completely cleared up
	 * 
	 * 
	 * 
	 * */
	var backstack = {
//		ghosturis: ['editor'],
		chronicle: [],
		// ignore e.g appui.setchanges
		nochanges: 0,
		onpopevent: function (e) {
//			$.log.s( 'backstack.onpopevent', backstack.locked );
			if (backstack.nochanges)
				backstack.nochanges = 0;
			
			if (backstack.locked)
				backstack.popandlock();
			else
				backstack.chronicle.pop();
		},
		/*
		 * marks locked as zero, no pushstate or back should be called during
		 * this state, if you do, it just pops one more entry
		 * 
		 * pops all items in the chronicle one by one
		 * does history.back once, then listens for popstate
		 * onpopevent calls popandlock again
		 * 
		 * once chronicle is empty, locked is marked as 0 again
		 * */
		locked: 0,
		crumbs: [],
		callback: 0,
		popandlock: function () {
//			$.log.s( 'backstack.popandlock' );

			if (backstack.chronicle.length) {
				backstack.chronicle.pop();
				history.back();
			} else {
				typeof backstack.callback === 'function' && backstack.callback();
				backstack.callback = 0;
			}
		},
		/*
		 * only works if chronicle is empty
		 * basically navigates to all breadcrumbs incrementially
		 * ? navigate to /attendance/students/one/2018-may-25
		 * 
		 * it'll insert these items into the back stack
		 * /attendance
		 * /attendance/student
		 * /attendance/students/one
		 * /attendance/students/one/2018-may-25
		 * 
		 * callback is called when all items are successfully pushed into stack
		 * */
		reconstruct: function (crumbs, callback) {
//			$.log.s( 'backstack.reconstruct' );

			callback = callback || appui.setchanges;
			backstack.locked = 1;
			crumbs = crumbs || [''];
			backstack.crumbs = crumbs;
			if (crumbs.length) {
				backstack.callback = function () {
					
					if (backstack.chronicle.length === 0) {
						backstack.pushstate('/');
						crumbs.forEach(function (crumb, i) {
							var currentcrumb = crumbs.slice(0, i+1);
							backstack.pushstate('/'+currentcrumb.join('/'));
						});
						
						backstack.locked = 0;
						typeof callback === 'function' && callback( crumbs );
					} else
						history.back();
				};
				backstack.popandlock();
			} else {
				backstack.callback = function () {
					if (backstack.chronicle.length === 0) {
						backstack.locked = 0;
						typeof callback === 'function' && callback( crumbs );
					} else
						history.back();
				};
				backstack.popandlock();
			}
		},
		pushstate: function (href, force) {
			href = href || location.pathname;
//			$.log.s( 'backstack.pushstate', href );

			if (location.pathname !== href || force) {
				lasturiuponpop = href;

				history.pushState(null, null, href);
				backstack.chronicle.push(href);
			}
			
		},
		replacestate: function (href) {
			history.replaceState(null, null, href);
		},
		/*
		 * no need to call appui.get here since dom+appui listen to popstate
		 * events anyway
		 * 
		 * nochanges makes sure that the popstate event generated by this back
		 * action is ignored once by appui.setchanges :p
		 * */
		back: function (nochanges) {
//			$.log.s( 'backstack.back' );

			backstack.nochanges = 1;
			
			backstack.chronicle.pop();
			history.back();
		},
	};
	Hooks.set('dompopstate', 'backstack', function (e) {
		backstack.onpopevent(e);
	});

	var chronicle = [];
	Backstack.entries = function () { // get a copy of the chronicle entries
		return [].concat(chronicle);
	};
	Backstack.entries_length = function () {
		return chronicle.length;
	};
	// override the original .back function
	var original_back_function = Backstack.back;
	Backstack.back = function () {
		if (chronicle.length || history.state) {
			$.log.w( 'history.back()' );
			history.back();
		}
		else {
			$.log.w( 'original_back_function()' );
			original_back_function();
		}
	};

	// NEW LOGIC
	// /Philosophy/Backstack.md
	function get_last_entry() {
		 return chronicle[ chronicle.length-2 ];
	}
	function get_current_entry() {
		 return chronicle[ chronicle.length-1 ];
//		 return { state: history.state, link: location.pathname };
	}

	function parse_link(link) {
		var is_main = link == '/', is_view, view_uid, is_sheet, sheet_uid, is_dialog, dialog_uid;
		var crumbs = location.pathname.split('/'), last_crumb = '';
		crumbs.forEach(function (crumb, i) {
			if (crumb.startsWith('-')) is_sheet = crumb.slice(1);
			else if (crumb.startsWith('?')) is_dialog = crumb.slice(1);
			else {
				if (last_crumb.startsWith('-')) {
					if (isundef(sheet_uid)) {
						sheet_uid = crumb;
					}
				} else if (last_crumb.startsWith('?')) {
					if (isundef(dialog_uid)) {
						dialog_uid = crumb;
					}
				} else if (i == 1) {
					is_view = crumb;
				} else if (i == 2 && isundef(view_uid)) {
					view_uid = crumb;
				}
			}
			
			last_crumb = crumb;
		});
		return { is_main, is_view, view_uid, is_sheet, sheet_uid, is_dialog, dialog_uid };
	}
	Backstack.parse = parse_link;
	function restore_crumbs(crumbs) {
		// your module should use this to maintain state silently
		// like triggering Sheet.cancel or Dialog.cancel helps dependent modules to cleanup temporary objects
		Hooks.run('backstack-crumbs', crumbs);
		
		if (crumbs.is_view) {
			Backstack.view({
				name: crumbs.is_view,
				uid: crumbs.view_uid,
			}, 1);
		} else if (crumbs.is_main) {
			if (!Backstack.is_main_in_startup()) {
				original_back_function();
			}

			Backstack.states.view = 0;
			Backstack.states.main = 1;
		}
		if (crumbs.is_sheet) {
			Backstack.sheet({
				name: crumbs.is_sheet,
				uid: crumbs.sheet_uid,
			}, 1);
		} else {
			Backstack.states.sheet = 0;
		}
		if (crumbs.is_dialog) {
			Backstack.dialog({
				name: crumbs.is_dialog,
				uid: crumbs.dialog_uid,
			}, 1);
		} else {
			Backstack.states.dialog = 0;
		}
	}

	var ignore_once; // for popstate, useful for reconstructing previous entries or reloading the current one
	listener('popstate', function (event) {
		// retrieve all states from the link
		var crumbs = parse_link( location.pathname );

		$.log.w( 'Backstate popstate', crumbs );
		if (chronicle.length) chronicle.pop();
		
		if (ignore_once) {
			$.log.w( 'Backstate ignoring once' );
			ignore_once = 0;
			return;
		}

		// TODO detect if it's a back or forward event
		if (event.state) {
			if (event.state.uuid > uuid) { // $.log( 'popstate forward' );
			} else { // $.log( 'popstate back' );
			}
		} else { // $.log( 'popstate back' );
		}
		var state = (event.state||{});
		uuid = state.uuid||uuid;

		restore_crumbs(crumbs);
	});
	// allows various simple and predictable use cases
	// push state should generate the link and state for the entire view>sheet>dialog stack
	// prefix "-" always opens a sheet
	// prefix "?" always opens a dialog
	// these prefixes are not allowed for other names
	// "-lounge" "-call" "-rooms" would just open a sheet
	// 		 main		view		view-uid	sheet			dialog					extra-uid
	// link: /			/call		/lounge		/-call-members	/?add-call-member		/<uid>
	// link: /			/rooms		/lounge		/-room-members	/?delete-room-member	/<uid>
	// link: /			/rooms					/-add-member							/<uid>
	// link: /			/accounts	/account-uid/-edit-account
	// for old code
	// link: /			/rooms		/lounge		/-missing-name	/?missing-id
	// TODO require sheets and dialogs to provide regenerable UIDs
	function push_state() {
		$.log.w( 'Backstack push_state' );
		var states = Backstack.states;
		var link = '/';
		var state = {
			uuid: ++uuid,
		};
		if (states.view) { // rooms
			var view_name = View.get();
			var view_uid = View.get_uid();
			// if it's a home view and no uid is present, then stay at root
			if (Webapp.is_home_view(view_name) && !view_uid) {
				
			} else {
				state.view = view_name;
				link += view_name+'/';
				if (view_uid) { // room-uid
					state.view_uid = view_uid;
					link += view_uid+'/';
				}
			}
		}
		if (states.sheet) { // (create) room
			var sheet_name = '-'+(Sheet.get_active() || 'missing-name');
			state.sheet = sheet_name;
			link += sheet_name+'/';
			var sheet_uid = Sheet.get_active_uid();
			if (sheet_uid) { // room-uid
				state.sheet_uid = sheet_uid;
				link += sheet_uid+'/';
			}
		}
		if (states.dialog) { // delete room?
			var dialog_name = '?'+(Dialog.get_name() || 'missing-name');
			state.dialog = dialog_name;
			link += dialog_name+'/';
			var dialog_uid = Dialog.get_uid();
			if (dialog_uid) { // room-uid
				state.dialog_uid = dialog_uid;
				link += dialog_uid+'/';
			}
		}

		// check if the current entry is the same as the one being pushed, if so, restore it silently
		var current_entry = get_current_entry();
		if (current_entry && current_entry.link && current_entry.link == link || location.pathname == link) {
			$.log.w( 'Backstack staying at current entry silenty' );
			return;
		}

		chronicle.push({ state, link });
		history.pushState( state, '', link );
	}
	
	// backstack-* hooks are refined and validate calls
	Hooks.set('backstack-dialog', function (args) {
		$.log.w( 'Backstack Dialog', args );
		push_state();
	});
	Hooks.set('backstack-sheet', function (args) {
		$.log.w( 'Backstack Sheet', args );
		push_state();
	});
	Hooks.set('backstack-view', function (args) {
		$.log.w( 'Backstack View', args );
		push_state();
	});
	Hooks.set('backstack-main', function (args) {
		$.log.w( 'Backstack Main', Backstack.is_main_in_startup() ? 'Startup' : '' );
		if (Backstack.is_main_in_startup()) {
			// ignore, dont push
		} else {
			push_state();
		}
	});
	Hooks.set('ready', function () {
		$.log.w( 'Backstack History Ready' );
		$.taxeer('backstack-history-ready', function () {
			var crumbs = parse_link( location.pathname );
			restore_crumbs(crumbs);
			Backstack.states.main = 1; // Testing
		}, 100);
	});
	
})();
